services:
    db-service:
        build: services/db-service
        image: ${PROJECT_NAME:-site-card}-db-service:latest
        environment:
            POSTGRES_DB: ${PGDATABASE}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "${PGPORT:-5432}:5432"
        volumes:
            - ./services/db-service/pgdata:/var/lib/postgresql/data
        networks:
            - ${PROJECT_NAME:-site-card}-net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $PGUSER -d $PGDATABASE"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    app-service:
        build: services/app-service
        env_file:
            - .env
        ports:
            - "${NGINX_HTTP_PORT:-9292}:9292"
            - "${NGINX_HTTPS_PORT:-9393}:9393"
        depends_on:
            db-service:
                condition: service_healthy
        restart: unless-stopped
        image: ${PROJECT_NAME:-site-card}-app-service:latest
        container_name: ${PROJECT_NAME:-site-card}-app-service
        volumes:
            - ./userdata:/userdata
            - ./certs:/certs
        networks:
            - ${PROJECT_NAME:-site-card}-net

    notification-bot:
        build: services/notification-bot
        env_file:
            - .env
        ports:
            - "${NOTIFICATION_BOT_PORT:-50051}:50051"
        depends_on:
            db-service:
                condition: service_healthy
        restart: unless-stopped
        image: ${PROJECT_NAME:-site-card}-notification-bot:latest
        container_name: ${PROJECT_NAME:-site-card}-notification-bot
        networks:
            - ${PROJECT_NAME:-site-card}-net

volumes:
    pgdata:
    certs:

networks:
    ${PROJECT_NAME:-site-card}-net:
        driver: bridge
